[#538] New Dark Mode Feature!
prmr/JetUML pull request #554
Opened 2024-06-18 16:33 UTC by jkcoding7

The dark mode feature can be toggled by navigating to the menu command View | Dark Mode

The dark mode styling is integrated in the code by:
1. CSS styling for UI components, such as MenuBar, ContextMenu, and node background colors.
2. A ColorScheme enum that determines the color scheme of diagram elements.

2024-06-20 18:05 UTC, prmr requested changes

2024-06-20 18:05 UTC, prmr commented on tipdata/tips/tip-38.json
> +    { "text": "You can turn [on/off] dark mode by navigating to the menu command View | Dark Mode." },
-> "You can turn dark mode on or off by..."

2024-06-20 18:20 UTC, jkcoding7 commented on src/org/jetuml/gui/EditorFrame.java
> +	private final String aDarkModeURL = getClass().getResource("DarkMode.css").toExternalForm();
This is from a poor understanding of what a URL is... the right suffix would be Path

2024-06-25 17:08 UTC, prmr approved these changes

2024-07-02 17:02 UTC, merged